core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('series/', views.SeriesListView.as_view(), name='series'),
    path('series/<int:pk>', views.SeriesDetailView.as_view(), name='series-detail'),
    
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]

urlpatterns += [
    path('chapter/create/', views.ChapterCreate.as_view(), name='chapter-create'),
    path('chapter/<int:pk>/update/', views.ChapterUpdate.as_view(), name='chapter-update'),
    path('chapter/<int:pk>/delete/', views.ChapterDelete.as_view(), name='chapter-delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

novlr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    ]
    
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='core/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models
from django.urls import reverse #used to generate URLs by reversing the url pattern
from ckeditor.fields import RichTextField

# Create your models here.
class NarrativeForm(models.Model):
    type = models.CharField(max_length=50, help_text='Fiction or Non Fiction')
    
    def __str__(self):
        """String representing the object"""
        return self.type

class Genre(models.Model):
    """Model representing a book genre"""
    name = models.CharField(max_length=200, help_text='Enter  book genre')

    
    def __str__(self):
        """String for representing the Model Object"""
        return self.name
        
class Book(models.Model):
    """Model representing a book."""
    title = models.CharField(max_length=200)
    BOOK_STATUS = (
        ('d', 'Draft'),
        ('a', 'Alpha'),
        ('b', 'Beta'),
        ('f', 'Final'),
    )
    status = models.CharField(
        max_length=1,
        choices=BOOK_STATUS,
        blank=True,
        default='d',
        help_text='Chapter Status',
    )
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    narrative = models.ForeignKey('NarrativeForm', on_delete=models.SET_NULL, help_text='Select if this is a work of fiction or non-fiction.', null=True)
    # Foreign Key for Author, which is a one to many relationship (one author to many books)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    
    series = models.ForeignKey('Series', on_delete=models.SET_NULL, null=True, blank=True)
    series_number = models.IntegerField(default=1, blank=True, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    
    
    
    
    def __str__(self):
        """String representing the Model Object"""
        return self.title
       
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book"""
        return reverse('book-detail', args=[str(self.id)])
        
        
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])
    
    display_genre.short_description = 'Genre'
    
class Chapter(models.Model):
    """Model representing a specific chapter in a book"""
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    number = models.IntegerField(default=1, blank=False, null=False)
    title = models.CharField(max_length=200)
    writing_status = (
        ('d', 'Draft'),
        ('a', 'Alpha'),
        ('b', 'Beta'),
        ('f', 'Final'),
    )
    body = RichTextField(config_name='awesome_ckeditor')
    
    status = models.CharField(
        max_length=1,
        choices=writing_status,
        blank=True,
        default='d',
        help_text='Chapter Status',
    )
    
    class Meta:
        ordering = ['number']
        
    def __str__(self):
        """String for representing the model object"""
        return f'{self.id} ({self.book.title})'
        
    def word_count(self):
        count = len(self.body.split())
        
        return count
        
class Author(models.Model):
    """Model representing the author"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    
    class Meta:
        ordering = ['last_name','first_name']
        
    def get_absolute_url(self):
        """Returns the URL to access the author instance"""
        return reverse('author-detail', args=[str(self.id)])
        
    def __str__(self):
        """String for representing the model object"""
        return f'{self.last_name}, {self.first_name}'
        
class Series(models.Model):
    """Model representing the author"""
    title = models.CharField(max_length=100)
    
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the Series')
           
    def get_absolute_url(self):
        """Returns the URL to access the author instance"""
        return reverse('series-detail', args=[str(self.id)])
        
    def __str__(self):
        """String for representing the model object"""
        return f'{self.title}'

core/forms.py
from django.forms import ModelForm
from core.models import Book, Series, Chapter

class NewBookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

core/views.py
from django.shortcuts import render
from core.models import Book, Author, Genre, Series, Chapter
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models.functions import Length

# Create your views here.

def index(request):
    """View function for home page of site."""
    
    #Generate counts of main objects
    num_books = Book.objects.all().count()
    num_chapters = Chapter.objects.all().count()
    
    #Finished Books (status = 'f')
    num_finished_books = Book.objects.filter(status__exact='f').count()
    
    # The all() is implied by default.
    num_authors = Author.objects.count()
    
    context = {
        'num_books': num_books,
        'num_chapters': num_chapters,
        'num_finished_books': num_finished_books,
        
    }
    
    return render(request, 'index.html', context=context)

class SeriesListView(generic.ListView):
    model = Series
    context_object_name = 'series_list'
    #queryset = Book.objects.filter(title__icontains='all')[:5]
    template_name = 'series/series_list.html'

class SeriesDetailView(generic.DetailView):
    model = Series
    paginate_by = 10
    context_object_name = 'series_detail'
    template_name = 'series/series_detail.html'

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    #queryset = Book.objects.filter(title__icontains='all')[:5]
    template_name = 'books/book_list.html'
    
class BookDetailView(generic.DetailView):
    model = Book
    paginate_by = 10
    template_name = 'books/book_detail.html'
    
class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    initial = {'status': 'd'}
    
class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    
class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')
    
class ChapterCreate(CreateView):
    model = Chapter
    fields = '__all__'
    initial = {'status': 'd'}
    
class ChapterUpdate(UpdateView):
    model = Chapter
    fields = '__all__'
    
class ChapterDelete(DeleteView):
    model = Chapter
    success_url = reverse_lazy('books')

core/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>A Writing Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <script type="text/javascript" src="{% static "js/jquery-1.12.4.js" %}"></script>
  <script type="text/javascript" src="{% static "js/jquery-ui.js" %}"></script>
  <script type="text/javascript" src="{% static "js/bootstrap.js" %}"></script>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body id="bootstrap-overrides">
	<header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">NOVLR</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'series' %}">Series</a>
            </li>
			<li class="nav-item">
              <a class="nav-link" href="{% url 'books' %}">Books</a>
            </li>	
          </ul>
          
		  <!--<form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>-->
		  
        </div>
      </nav>
    </header>
	

	<!-- Begin page content -->

		<div class="col-sm-offset-1 col-sm-10" style="margin-top: 7em">{% block content %}{% endblock %}
		{% block pagination %}
		{% if is_paginated %}
			<div class="pagination">
				<span class="page-links">
					{% if page_obj.has_previous %}
						<a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
					{% endif %}
					<span class="page-current">
						Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
					</span>
					{% if page_obj.has_next %}
						<a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
					{% endif %}
				</span>
			</div>
		{% endif %}
		{% endblock %}
	  </div>
	

</body>
</html>

core/templates/books/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    <!--Header section of the book -->
    <h1>{{ book.title }}</h1>
    <div class="row">
		<div class="col-sm-4"><strong>Genre:</strong> {{ book.genre.all|join:", " }}</div>
		<div class="col-sm-4"><strong>Series:</strong> {{ book.series }}</div>
		<div class="col-sm-4"><strong>Current Status:</strong> {{ book.get_status_display }}</div>
	</div>
    <div class="row">
		<div class="col-sm-12"><strong>Summary:</strong> {{ book.summary }}</div>
	</div>
	<hr></br>

	<!--Collapsible Chapter sections-->
	<div class="col-md-10">
		<h3 class=" text-black">Chapters</h2>
		<span class="loader pull-right"><span class="loader-inner"></span></span>
		<hr></br>
		{% for chapter in book.chapter_set.all %}			
			<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
				<div class="panel panel-default">
				
					<div class="panel panel-default">
					<div class="panel-heading" role="tab" id="heading{{ chapter.number }}">
						<h4 class="panel-title">
							<a class="collapsed{{ chapter.number }}" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ chapter.number }}" aria-expanded="true" aria-controls="collapse{{ chapter.number }}">
								<strong>{{ chapter.number }} - {{ chapter.title }} </strong>
								<span  style="font-size: .8em; padding-left:2%;" class="{% if chapter.status == 'f' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">
									{{ chapter.get_status_display }}
								</span>
								
								<span style="font-size: .6em; padding-left:2%;"> {{ chapter.word_count }} words </span>
								
							</a>
						</h4>
						
					</div>
					<div id="collapse{{ chapter.number }}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading{{ chapter.number }}">
						<div class="panel-body">
							<p>{{ chapter.body|safe }}</p>
						</div>
					</div>
				</div>
			</div>
					
		{% endfor %}
	</div>

  </div>
{% endblock %}



	

core/templates/books/book_list.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Book List</h1>
	{% if book_list %}
		{% for book in book_list %}
			<div class="card" style="width: 25rem; height: 35rem;">
			  <!--<img src="{{ book.cover.url }}" class="card-img-top" alt="...">-->
			  <div class="card-body">
				<h5 class="card-title">{{ book.title }}</h5>
				<p class="card-text">{{ book.summary }}</p>
				<a href="{{ book.get_absolute_url }}" class="btn btn-primary">Start Reading</a>
				<p><i>Currently in {{ book.get_status_display }} status</i></p>
			  </div>
			</div>
		{% endfor %}
	{% else %}
		<p>There are no books to read at this point.</p>
	{% endif %}       
{% endblock %}

core/templates/core/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

core/templates/core/book_form_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

core/templates/core/chapter_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

core/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>I'm really at a loss for what to put here</h1>
  <p>Hello and welcome to my writing corner. Here, my friend, you will find my forrays into fictions of fantasy. </p>
  <h2>Currently Available:</h2>
  <p>The page has {{ num_books }} books, containing {{ num_chapters }} chapters.</p>
  <p>Stop by soon as I continue to develop this site and upload my work</p>
 
{% endblock %}

core/templates/series/series_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    <!--Header section of the Series -->
    <h1>{{ series.title }}</h1>
    <!--<div class="row">
		<div class="col-sm-4"><strong>Genre:</strong> {{ book.genre.all|join:", " }}</div>
		<div class="col-sm-4"><strong>Series:</strong> {{ book.series }}</div>
		<div class="col-sm-4"><strong>Current Status:</strong> {{ book.get_status_display }}</div>
	</div>
    <div class="row">
		<div class="col-sm-12"><strong>Summary:</strong> {{ book.summary }}</div>
	</div>-->
	<hr></br>

	<!--Collapsible Book sections-->
	<div class="col-md-10">
		<h3 class=" text-black">Books</h2>
		<span class="loader pull-right"><span class="loader-inner"></span></span>
		<hr></br>
		{% for book in book_list %}
		  {% if book.series.title == series.title %}
			<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
				<div class="panel panel-default">				
					<div class="panel panel-default">
						<div class="panel-heading" role="tab" id="heading{{ chapter.number }}">
							<h4 class="panel-title">
								<a class="collapsed{{ chapter.number }}" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ chapter.number }}" aria-expanded="true" aria-controls="collapse{{ chapter.number }}">
									<strong>{{ book.title }}</strong>
									<span  style="font-size: .8em; padding-left:2%;" class="{% if chapter.status == 'f' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">
										{{ book.get_status_display }}
									</span>
									<a href="{{ book.get_absolute_url }}" class="btn btn-primary">Start Reading</a>
								</a>
							</h4>
						</div>
						<!--<div id="collapse{{ chapter.number }}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading{{ chapter.number }}">
						<div class="panel-body">
							<a href="{{ book.get_absolute_url }}" class="btn btn-primary">Start Reading</a>
						</div>-->
					</div>
				</div>
			</div>
			{% endif %}
		{% endfor %}
	</div>

  </div>
{% endblock %}



	

core/templates/series/series_list.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Series List</h1>
	{% if series_list %}
		{% for series in series_list %}
			<div class="card" style="width: 25rem; height: 35rem;">
			  <!--<img src="..." class="card-img-top" alt="...">-->
			  <div class="card-body">
				<h5 class="card-title">{{ series.title }}</h5>
				<p class="card-text">Series Summary</p>
				<!--<a href="{{ series.get_absolute_url }}" class="btn btn-primary">Go to Series Page</a>-->
			  </div>
			</div>
		{% endfor %}
	{% else %}
		<p>There are no books to read at this point.</p>
	{% endif %}       
{% endblock %}